/********************************************************************
* Kazu_crapCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Kazu_crapCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableKazu_crapCint();
extern void G__cpp_setup_inheritanceKazu_crapCint();
extern void G__cpp_setup_typetableKazu_crapCint();
extern void G__cpp_setup_memvarKazu_crapCint();
extern void G__cpp_setup_globalKazu_crapCint();
extern void G__cpp_setup_memfuncKazu_crapCint();
extern void G__cpp_setup_funcKazu_crapCint();
extern void G__set_cpp_environmentKazu_crapCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/Users/yuntse/Work/uboone/LArLite/UserDev/Kazu/crap/sample.h"
#include "/Users/yuntse/Work/uboone/LArLite/UserDev/Kazu/crap/yuntse.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Kazu_crapCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Kazu_crapCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Kazu_crapCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Kazu_crapCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Kazu_crapCintLN_sample;
extern G__linked_taginfo G__Kazu_crapCintLN_yuntse;

/* STUB derived class for protected member access */
